version: '3'

services:
  example-service:
    build:
      context: .
      args:
        NODE_ENV: production
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    command: npm run start
