version: '3'

services:
  example-service-debug:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run start:debug
